import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-10">
          <main className="border border-gray-500 p-10">
            {/* <main className="flex h-[calc(100vh-10px)] flex-col items-left justify-between iv border border-gray-500 bg-gradient-to-b p-10"> */}
            {/* <div className="w-full max-w-5xl items-center justify-between font-mono"> */}
            <Navbar />
            {children}
            {/* </div> */}
          </main>
        </div>
      </body>
    </html>
  );
}
